aotassemblies=false
androidaddkeepalives=
androidaotmode=interpreter
androidembedprofilers=
androidenableprofiledaot=
androiddextool=d8
androidlinktool=
androidlinkresources=
androidpackageformat=apk
embedassembliesintoapk=false
androidlinkmode=none
androidlinkskip=
androidsdkbuildtoolsversion=35.0.0
androidsdkpath=c:\program files (x86)\android\android-sdk\
androidndkpath=
javasdkpath=c:\program files\android\openjdk\jdk-21.0.8\
androidsequencepointsmode=none
androidnetsdkversion=35.0.105
monosymbolarchive=false
androiduselatestplatformsdk=false
targetframeworkversion=v9.0
androidcreatepackageperabi=
androidgeneratejnimarshalmethods=false
os=windows_nt
androidincludedebugsymbols=true
androidpackagenamingpolicy=lowercasecrc64
_nugetassetsfilehash=14e7ddf5fa61fa6fb7fb15bbcf2e37d39d0a6c0c319d89eca2d6a02e221fc6c6
typemapkind=strings-asm
androidmanifestplaceholders=
projectfullpath=c:\users\dguil\documents\repo\sports-betting-analyzer\mobile\sportsbettinganalyzer.mobile.csproj
androidusedesignerassembly=true
