import os

file_path = r'c:\Users\dguil\source\repos\PythonMLService\backend\scripts\nba_importer.py'

# Open with utf-8 to handle any special characters
try:
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
except UnicodeDecodeError:
    # Fallback to cp1252 if utf-8 fails
    with open(file_path, 'r', encoding='cp1252') as f:
        lines = f.readlines()

new_lines = []
target_func = 'async def import_game_logs_via_nba_api'
found_start = -1

for i, line in enumerate(lines):
    if target_func in line:
        found_start = i
        break

if found_start != -1:
    # Keep everything before the corrupted function
    content = lines[:found_start]
    
    # Append a fresh, clean version of that function and the end of file
    content.append('async def import_game_logs_via_nba_api(conn, sport_id: int, progress_callback=None) -> dict:\n')
    content.append('    """Import NBA player game logs for hit rate calculations."""\n')
    content.append('    try:\n')
    content.append('        from nba_api.stats.endpoints import leaguegamelog\n')
    content.append('        import time\n')
    content.append('    except ImportError:\n')
    content.append('        logger.warning("nba_api not installed - skipping game logs")\n')
    content.append('        return {"imported": 0}\n')
    content.append('    \n')
    content.append('    if progress_callback:\n')
    content.append('        progress_callback("Loading NBA player game logs for hit rates...")\n')
    content.append('    \n')
    content.append('    imported = 0\n')
    content.append('    \n')
    content.append('    try:\n')
    content.append('        # Load game logs by season\n')
    content.append('        seasons = ["2023-24", "2024-25"]\n')
    content.append('        \n')
    content.append('        all_logs = []\n')
    content.append('        for season in seasons:\n')
    content.append('            try:\n')
    content.append('                if progress_callback:\n')
    content.append('                    progress_callback(f"Loading NBA game logs for {season}...")\n')
    content.append('                \n')
    content.append('                # Get player game logs for the season\n')
    content.append('                game_log = leaguegamelog.LeagueGameLog(\n')
    content.append('                    season=season,\n')
    content.append('                    player_or_team_abbreviation=\'P\',  # Player logs\n')
    content.append('                    season_type_all_star=\'Regular Season\'\n')
    content.append('                )\n')
    content.append('                logs_df = game_log.get_data_frames()[0]\n')
    content.append('                \n')
    content.append('                if logs_df is not None and len(logs_df) > 0:\n')
    content.append('                    all_logs.append(logs_df)\n')
    content.append('                    logger.info(f"Loaded {len(logs_df)} game records for {season}")\n')
    content.append('                \n')
    content.append('                time.sleep(1)  # Rate limit\n')
    content.append('                \n')
    content.append('            except Exception as e:\n')
    content.append('                logger.warning(f"Error loading {season} game logs: {e}")\n')
    content.append('                continue\n')
    content.append('        \n')
    content.append('        if not all_logs:\n')
    content.append('            logger.warning("No NBA game logs loaded")\n')
    content.append('            return {"imported": 0}\n')
    content.append('        \n')
    content.append('        logs_df = pd.concat(all_logs, ignore_index=True)\n')
    content.append('        \n')
    content.append('        if progress_callback:\n')
    content.append('            progress_callback(f"Processing {len(logs_df)} NBA game log records...")\n')
    content.append('        \n')
    content.append('        for i, (_, row) in enumerate(logs_df.iterrows()):\n')
    content.append('            if progress_callback and i % 500 == 0:\n')
    content.append('                progress_callback(f"Importing NBA game logs {i}/{len(logs_df)}...")\n')
    content.append('            \n')
    content.append('            player_id = row.get(\'PLAYER_ID\')\n')
    content.append('            game_id = row.get(\'GAME_ID\')\n')
    content.append('            if pd.isna(player_id) or pd.isna(game_id):\n')
    content.append('                continue\n')
    content.append('            \n')
    content.append('            def safe_val(val):\n')
    content.append('                if pd.isna(val):\n')
    content.append('                    return None\n')
    content.append('                if isinstance(val, float):\n')
    content.append('                    return int(val) if val == int(val) else round(val, 2)\n')
    content.append('                return val\n')
    content.append('            \n')
    content.append('            # Extract season year\n')
    content.append('            season_id = row.get(\'SEASON_ID\', \'\')\n')
    content.append('            season_year = int(season_id[1:5]) if len(str(season_id)) >= 5 else 2024\n')
    content.append('            \n')
    content.append('            metadata = {\n')
    content.append('                \'player_id\': str(player_id),\n')
    content.append('                \'game_id\': str(game_id),\n')
    content.append('                \'player_name\': safe_val(row.get(\'PLAYER_NAME\')),\n')
    content.append('                \'team\': safe_val(row.get(\'TEAM_ABBREVIATION\')),\n')
    content.append('                \'game_date\': safe_val(row.get(\'GAME_DATE\')),\n')
    content.append('                \'matchup\': safe_val(row.get(\'MATCHUP\')),\n')
    content.append('                \'wl\': safe_val(row.get(\'WL\')),\n')
    content.append('                \'min\': safe_val(row.get(\'MIN\')),\n')
    content.append('                \'pts\': safe_val(row.get(\'PTS\')),\n')
    content.append('                \'reb\': safe_val(row.get(\'REB\')),\n')
    content.append('                \'ast\': safe_val(row.get(\'AST\')),\n')
    content.append('                \'stl\': safe_val(row.get(\'STL\')),\n')
    content.append('                \'blk\': safe_val(row.get(\'BLK\')),\n')
    content.append('                \'tov\': safe_val(row.get(\'TOV\')),\n')
    content.append('                \'fgm\': safe_val(row.get(\'FGM\')),\n')
    content.append('                \'fga\': safe_val(row.get(\'FGA\')),\n')
    content.append('                \'fg3m\': safe_val(row.get(\'FG3M\')),\n')
    content.append('                \'fg3a\': safe_val(row.get(\'FG3A\')),\n')
    content.append('                \'ftm\': safe_val(row.get(\'FTM\')),\n')
    content.append('                \'fta\': safe_val(row.get(\'FTA\')),\n')
    content.append('                \'plus_minus\': safe_val(row.get(\'PLUS_MINUS\')),\n')
    content.append('            }\n')
    content.append('            \n')
    content.append('            metadata = {k: v for k, v in metadata.items() if v is not None}\n')
    content.append('            \n')
    content.append('            content_hash = compute_hash({\n')
    content.append('                \'sport\': \'nba\',\n')
    content.append('                \'player_id\': str(player_id),\n')
    content.append('                \'game_id\': str(game_id),\n')
    content.append('                \'type\': \'game_log\'\n')
    content.append('            })\n')
    content.append('            \n')
    content.append('            try:\n')
    content.append('                await conn.execute(\n')
    content.append('                    """INSERT INTO results (sport_id, season, series, metadata, content_hash)\n')
    content.append('                       VALUES ($1, $2, \'nba_game_log\', $3, $4)\n')
    content.append('                       ON CONFLICT (content_hash) WHERE content_hash IS NOT NULL\n')
    content.append('                       DO UPDATE SET metadata = EXCLUDED.metadata""",\n')
    content.append('                    sport_id, season_year, json.dumps(metadata), content_hash\n')
    content.append('                )\n')
    content.append('                imported += 1\n')
    content.append('            except Exception as e:\n')
    content.append('                logger.debug(f"Error importing NBA game log: {e}")\n')
    content.append('            \n')
    content.append('            if i % 1000 == 0:\n')
    content.append('                gc.collect()\n')
    content.append('        \n')
    content.append('        logger.info(f"Imported {imported} NBA game logs")\n')
    content.append('        return {"imported": imported}\n')
    content.append('        \n')
    content.append('    except Exception as e:\n')
    content.append('        logger.error(f"Error importing NBA game logs: {e}")\n')
    content.append('        return {"imported": 0, "error": str(e)}\n')
    content.append('\n')
    content.append('if __name__ == "__main__":\n')
    content.append('    async def test_import():\n')
    content.append('        def log_progress(msg):\n')
    content.append('            print(f"[PROGRESS] {msg}")\n')
    content.append('        \n')
    content.append('        result = await import_all_nba(clear_existing=True, progress_callback=log_progress)\n')
    content.append('        print(f"Result: {result}")\n')
    content.append('    \n')
    content.append('    asyncio.run(test_import())\n')

    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(content)
    print("SUCCESS: File definitively restored.")
else:
    print("CRITICAL ERROR: Function signature not found.")
